---
title: "Comparisons with HH"
author: "Shreya"
date: "2024-12-11"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

knitr::opts_chunk$set(fig.width = 10, fig.height = 6)
```

```{r data and setup}

library(stringr)
library(survey)
library(tidyr)
library(dplyr)
library(readr)
library(readxl)
library(ggplot2)
library(knitr)
library(kableExtra)
library(tibble)
library(naniar)
library(purrr)
library(patchwork)
library(moments)
       
var_lables <- read_csv('workplace/Data/variable_descriptions_workplace.csv')
factor_levels <- read_csv('workplace/Data/factor_labels_workplace.csv')

workplace_df <- read_csv("workplace/Data/Workplace_Survey_Cleaned.csv") 
# workplace_df <- workplace_df[,13:146]

data_cols <- c(
  "...1", "start", "end", "username", "today", "deviceid", "int_date", "int_time_now", 
  "int_time_once", "int_time", "consent_inp_yes", "consent_inp_no", "consent_no_others", 
  "elig_adult", "elig_working", "interview_lang", "perinf_age", "perinf_gender", 
  "perinf_edu_stat", "perinf_edu_lvl", "perinf_grad_degr", "perinf_diploma", 
  "perinf_emp_stat", "perinf_occ_seo", "perinf_occ_see", "perinf_occ_gov", 
  "perinf_occ_pvt", "perinf_occ_wage", "perinf_occ_gig", "perinf_occ_inf", 
  "perinf_ind", "perinf_manuf", "perinf_home_wrk_loc", "comm_commute_location", 
  "perinf_wrk_locality", "perinf_wrk_streetname", "prinf_wrk_landmark", 
  "perinf_wrk_locality_mult", "perinf_wrk_streetname_mult", "prinf_wrk_landmark_mult", 
  "perinf_home_locality", "perinf_home_streetname", "prinf_home_landmark", 
  "prinf_tot_hh_mem", "perinf_tot_rooms", "perinf_asset_ro", "perinf_state_from", 
  "perinf_mig_stat", "perinf_prev_loc", "perinf_mig_reason", "perinf_mig_reason_1", 
  "perinf_mig_reason_2", "perinf_mig_reason_3", "perinf_mig_reason_4", 
  "perinf_mig_reason_5", "perinf_mig_reason_6", "perinf_mig_reason_7", 
  "perinf_mig_reason_8", "perinf_mig_reason_9", "perinf_mig_reason_10", 
  "perinf_mig_reason_11", "perinf_mig_reason_9997", "perinf_mig_reason_9998", 
  "perinf_mig_reason_9999", "perinf_caste", "perinf_caste_name_nm", 
  "perinf_caste_name_m", "perinf_religion", "empl_se_income", "empl_salary", 
  "empl_gig_income", "empl_gig_days", "empl_wage_days", "empl_wage_earnings", 
  "empl_freq_pymnt", "empl_freq_pymnt_others", "empl_earnings_w", 
  "empl_earnings_bm", "empl_earnings_m", "empl_earnings_o", "empl_entsize_emp", 
  "empl_benefits_see", "empl_benefits_see_1", "empl_benefits_see_2", 
  "empl_benefits_see_3", "empl_benefits_see_4", "empl_benefits_see_9998", 
  "empl_benefits_see_9999", "empl_ent_type", "empl_job_contract", 
  "empl_benefits_emp", "empl_benefits_emp_1", "empl_benefits_emp_2", 
  "empl_benefits_emp_3", "empl_benefits_emp_4", "empl_benefits_emp_9998", 
  "empl_benefits_emp_9999", "empl_paid_leave", "empl_wrkplace_size_emp", 
  "empl_wrk_toil_access", "empl_wrk_water_access", "comm_commute_days", 
  "comm_work_dist", "comm_ow_time", "comm_work_dist_mult", "comm_time_mult", 
  "comm_mode_travel", "comm_mode_travel_1", "comm_mode_travel_2", 
  "comm_mode_travel_3", "comm_mode_travel_4", "comm_mode_travel_5", 
  "comm_mode_travel_6", "comm_mode_travel_7", "comm_mode_travel_8", 
  "comm_mode_travel_9", "comm_mode_travel_10", "comm_mode_travel_11", 
  "comm_mode_travel_12", "comm_mode_travel_13", "comm_mode_travel_14", 
  "comm_mode_travel_15", "comm_mode_travel_9998", "comm_mode_travel_9999", 
  "comm_travel_cost", "comm_travel_subsidy", "comm_travel_subsidy_oth", 
  "comm_travel_difficulty_yn", "comm_travel_difficulty", "comm_travel_difficulty_1", 
  "comm_travel_difficulty_2", "comm_travel_difficulty_3", "comm_travel_difficulty_4", 
  "comm_travel_difficulty_5", "comm_travel_difficulty_6", "comm_travel_difficulty_7", 
  "comm_travel_difficulty_8", "comm_travel_difficulty_9", "comm_travel_difficulty_9997", 
  "comm_travel_difficulty_9998", "comm_travel_difficulty_9999", "survey_id", 
  "int_enum_id", "int_enum_name", "int_clust_id", "int_clust_name", 
  "int_oth_clust_name", "int_interview_location", "X._int_interview_location_latitude", 
  "X._int_interview_location_longitude", "X._int_interview_location_altitude", 
  "X._int_interview_location_precision", "int_note_img_no_revisit_location", 
  "int_place_image", "int_place_image_URL", "X._id", "X._uuid", "X._submission_time", 
  "X._validation_status", "X._notes", "X._status", "X._submitted_by", "X.__version", 
  "X._tags", "X._index"
)

data_cols_drop <- c(
  "...1", "start", "end", "username", 
  "today", "deviceid", "int_date", "int_time_now", 
  "int_time_once", "int_time", "consent_inp_yes", "consent_inp_no", 
  "int_clust_name", "int_oth_clust_name", "int_interview_location", 
  "X._int_interview_location_latitude", "X._int_interview_location_longitude", 
  "X._int_interview_location_altitude", "X._int_interview_location_precision", 
  "int_note_img_no_revisit_location", "int_place_image", "int_place_image_URL", 
  "X._id", "X._uuid", "X._submission_time", "X._validation_status", 
  "X._notes", "X._status", "X._submitted_by", "X.__version", 
  "X._tags", "X._index"
)

data_cols <- setdiff(data_cols,data_cols_drop)

data_cols_not_cat <- c("perinf_name","perinf_age",
                       "perinf_wrk_locality","perinf_wrk_streetname","perinf_wrk_landmark",
                       "perinf_wrk_locality_mult","perinf_wrk_streetname_mult","prinf_wrk_landmark_mult",
                       "perinf_home_locality","perinf_home_streetname","prinf_home_landmark","comm_travel_subsidy_ot",
                       "empl_freq_pymnt_others")

data_cols_cat <- setdiff(data_cols,data_cols_not_cat) 


workplace_df <- workplace_df%>%
  select(-(all_of(data_cols_drop)))%>%
  mutate(
   across(all_of(data_cols_cat), as.factor)
  )        


df_hh_joined <- read.csv("household/Data/CMDA_SDEIC_HH_imputed.csv")

#Reading Joined Data with Income variable

df_hh_income<- read_csv("household/Data/Joined Data-with_income.csv")%>%
  select("uuid", "combined_income_c")

df_hh_joined$combined_income_c <- df_hh_income$combined_income_c

#defining age groups

df_hh_joined <- df_hh_joined %>% mutate(
  age_group = case_when(
    hhr_age <1 ~ "Less than one",
    between(hhr_age,1,14) ~ "1 to 14",
    between(hhr_age,15,20) ~ "15 to 20",
    between(hhr_age,21,30) ~ "21 to 30",
    between(hhr_age,31,40) ~ "31 to 40",
    between(hhr_age,41,50) ~ "41 to 50",
    between(hhr_age,51,60) ~ "51 to 60",
    between(hhr_age,61,70) ~ "61 to 70",
    hhr_age>70 ~ "Above 70",
    .default = "Others"
  )
)


#setting survey design

design <- svydesign(id = ~final_svy_block, strata = ~final_stratum, weights = ~hh_weight, data = df_hh_joined, nest = TRUE) 


```



#Distribution of HH size comparison across both surveys
```{r HH Size}


# Assuming your data is stored in a data frame df with a column "age"
# Create the histogram with median line and labels
p1 <- 
  ggplot(df_hh_joined, aes(x = hi_hhsize)) + 
  geom_histogram(binwidth = 1, fill = "steelblue", color = "black") + 
  geom_vline(aes(xintercept = median(hi_hhsize, na.rm = TRUE)),
             color = "red", size = 1, linetype = "dashed") + 
  annotate("text", x = median(df_hh_joined$hi_hhsize, na.rm = TRUE), y = 0, 
           label = sprintf("Median: %.2f", median(df_hh_joined$hi_hhsize, na.rm = TRUE)),
           vjust = -0.5, color = "red") +  # Optional: Add label for the median
  labs(title = "HHistogram of HH_size (household)", x = "Age", y = "Count") +
  scale_x_continuous(breaks = seq(min(df_hh_joined$hi_hhsize, na.rm = TRUE), 10, by = 1)) +  # Set breaks to all integers
  theme_minimal()

workplace_df$prinf_tot_hh_mem <- as.numeric(workplace_df$prinf_tot_hh_mem)

# Create the histogram with median line and labels
p2 <- 
  ggplot(workplace_df, aes(x = prinf_tot_hh_mem)) + 
  geom_histogram(binwidth = 1, fill = "steelblue", color = "black") + 
  geom_vline(aes(xintercept = median(prinf_tot_hh_mem, na.rm = TRUE)),
             color = "red", size = 1, linetype = "dashed") + 
  annotate("text", x = median(workplace_df$prinf_tot_hh_mem, na.rm = TRUE), y = 0, 
           label = sprintf("Median: %.2f", median(workplace_df$prinf_tot_hh_mem, na.rm = TRUE)),
           vjust = -0.5, color = "red") +  # Optional: Add label for the median
  labs(title = "Histogram of HH_size (workplace)", x = "Age", y = "Count") +
  scale_x_continuous(breaks = seq(min(workplace_df$prinf_tot_hh_mem, na.rm = TRUE), 10, by = 1)) +  # Set breaks to all integers
  theme_minimal()


p1 +p2

```



```{r Number of rooms}
# Assuming your data is stored in a data frame df with a column "age"


# Create the histogram with median line and labels
p1 <- 
  ggplot(df_hh_joined, aes(x = hi_rooms)) + 
  geom_histogram(binwidth = 1, fill = "steelblue", color = "black") + 
  geom_vline(aes(xintercept = median(hi_rooms, na.rm = TRUE)),
             color = "red", size = 1, linetype = "dashed") + 
  annotate("text", x = median(df_hh_joined$hi_rooms, na.rm = TRUE), y = 0, 
           label = sprintf("Median: %.2f", median(df_hh_joined$hi_rooms, na.rm = TRUE)),
           vjust = -0.5, color = "red") +  # Optional: Add label for the median
  labs(title = "HHistogram of HH_size (household)", x = "Age", y = "Count") +
  scale_x_continuous(breaks = seq(min(df_hh_joined$hi_rooms, na.rm = TRUE), 10, by = 1)) +  # Set breaks to all integers
  theme_minimal()

workplace_df$perinf_tot_rooms <- as.numeric(workplace_df$perinf_tot_rooms)

# Create the histogram with median line and labels
p2 <- 
  ggplot(workplace_df, aes(x = perinf_tot_rooms)) + 
  geom_histogram(binwidth = 1, fill = "steelblue", color = "black") + 
  geom_vline(aes(xintercept = median(perinf_tot_rooms, na.rm = TRUE)),
             color = "red", size = 1, linetype = "dashed") + 
  annotate("text", x = median(workplace_df$perinf_tot_rooms, na.rm = TRUE), y = 0, 
           label = sprintf("Median: %.2f", median(workplace_df$perinf_tot_rooms, na.rm = TRUE)),
           vjust = -0.5, color = "red") +  # Optional: Add label for the median
  labs(title = "Histogram of HH_size (workplace)", x = "Age", y = "Count") +
  scale_x_continuous(breaks = seq(min(workplace_df$perinf_tot_rooms, na.rm = TRUE), 10, by = 1)) +  # Set breaks to all integers
  theme_minimal()

p1+p2

```


```{r}
factor_levels_hh <- read.csv("household/Data/factor_labels.csv")

options(digits = 2)

ent_size_hh <- df_hh_joined%>%
  group_by(hhr_entsize)%>%
  summarise(count = n())%>%
  filter(!is.na(hhr_entsize))%>%
  mutate(percentage = count/sum(count)*100)%>%
  left_join(
    factor_levels_hh %>%
      filter(variable == "hhr_entsize"),
    by = c("hhr_entsize" = "level") 
    )%>%
  select(-variable,-hhr_entsize) %>% 
  rename(hhr_entsize_label = label) 

ent_size_hh$hhr_entsize_label <- str_wrap(as.character(ent_size_hh$hhr_entsize_label), width = 10)
         
p1 <- ggplot(ent_size_hh, aes(x = hhr_entsize_label, y = count)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Enterprise Size for SEE in HH survey",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

ent_size_wp <- workplace_df %>%
  group_by(empl_entsize_emp) %>%
  summarise(count = n()) %>%
  filter(!is.na(empl_entsize_emp)) %>%
  mutate(percentage = count / sum(count) * 100) %>%
  mutate(empl_entsize_emp = factor(empl_entsize_emp)) %>%  # Ensure empl_entsize_emp is a factor
  left_join(
    factor_levels %>%
      filter(variable == "empl_entsize_emp") %>%
      mutate(level = factor(level)),  # Ensure level is also a factor
    by = c("empl_entsize_emp" = "level")
  ) %>%
  select(-variable, -empl_entsize_emp) %>% 
  rename(empl_entsize_emp_label = label)

ent_size_wp$empl_entsize_emp_label <- str_wrap(as.character(ent_size_wp$empl_entsize_emp_label), width = 10)

p2 <- ggplot(ent_size_wp, aes(x = empl_entsize_emp_label, y = count)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Enterprise Size for SEE in Workplace survey",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )


print(p1+p2)
```

```{r}


empl_security <- svytable(~hhr_job_contract, design)

empl_security <- as.data.frame(empl_security) %>%
  mutate(percentage = round(Freq/sum(Freq)*100,2),
        hhr_job_contract = 
           case_when(hhr_job_contract == -9999 ~ "Refuse", 
                     hhr_job_contract == -9998 ~ "Don't know",
                     hhr_job_contract == 1 ~ "With contract",
                     hhr_job_contract == 2 ~ "Without contract", 
                     TRUE ~ NA))

p1 <- 
  ggplot(empl_security, aes(x = hhr_job_contract, y = Freq)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Job contract - HH",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

es_wp <- workplace_df%>%
  group_by(empl_job_contract)%>%
  summarise(count = n())%>%
  filter(!is.na(empl_job_contract))%>%
    mutate(percentage = round(count/sum(count)*100,2),
        empl_job_contract = 
           case_when(empl_job_contract == -9999 ~ "Refuse", 
                     empl_job_contract == -9998 ~ "Don't know",
                     empl_job_contract == 1 ~ "With contract",
                     empl_job_contract == 2 ~ "Without contract", 
                     TRUE ~ NA))
  
p2 <- 
  ggplot(es_wp, aes(x = empl_job_contract, y = count)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Job contract - HH",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

p1 + p2

#---------------------------------------------


```

```{r}
#--------------------------------------------------------

paid_leave <- svytable(~hhr_paid_leave,design) %>% as.data.frame()%>%
  mutate(percentage = round(Freq/sum(Freq)*100,2),
        hhr_paid_leave = case_when(
                     hhr_paid_leave == "1" ~ "With paid leave",
                     hhr_paid_leave == "2" ~ "Without paid leave", 
                     TRUE ~ NA))

paid_leave$hhr_paid_leave <- str_wrap(as.character(paid_leave$hhr_paid_leave), width = 10)
      

p1 <- 
  ggplot(paid_leave, aes(x = hhr_paid_leave, y = Freq)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Paid Leave - HH",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

es_wp <- workplace_df%>%
  group_by(empl_paid_leave)%>%
  summarise(count = n())%>%
  filter(!is.na(empl_paid_leave))%>%
  mutate(percentage = round(count/sum(count)*100,2),
        empl_paid_leave = case_when(
                     empl_paid_leave == "1" ~ "With paid leave",
                     empl_paid_leave == "2" ~ "Without paid leave", 
                     TRUE ~ NA))

es_wp$empl_paid_leave <- str_wrap(as.character(es_wp$empl_paid_leave), width = 10)
  
p2 <- 
  ggplot(es_wp, aes(x = empl_paid_leave, y = count)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Paid Leave - WP",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

p1 + p2




```

```{r}
pf <- svytable(~hhr_benefits_emp_1,design) %>% as.data.frame() %>%
  mutate(percentage = round(Freq/sum(Freq)*100,2),
         hhr_benefits_emp_1 = case_when(hhr_benefits_emp_1 == "1" ~ "With PF",
                   hhr_benefits_emp_1 == "0" ~ "Without PF",
                     TRUE ~ NA))

pf$hhr_benefits_emp_1 <- str_wrap(as.character(pf$hhr_benefits_emp_1), width = 10)

p1 <- 
  ggplot(pf, aes(x = hhr_benefits_emp_1, y = Freq)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "PF - HH",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

pf_wp <- workplace_df%>%
  group_by(empl_benefits_emp_1)%>%
  summarise(count = n())%>%
  filter(!is.na(empl_benefits_emp_1))%>%
    mutate(percentage = round(count/sum(count)*100,2),
           empl_benefits_emp_1 = case_when(empl_benefits_emp_1 == "1" ~ "With PF",
                                          empl_benefits_emp_1 == "0" ~ "Without PF",
                                          TRUE ~ NA))
pf_wp$empl_benefits_emp_1 <- str_wrap(as.character(pf_wp$empl_benefits_emp_1), width = 10)
p2 <- 
  ggplot(pf_wp, aes(x = empl_benefits_emp_1, y = count)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "PF- WP",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

p1 + p2



```

```{r}
gratuity <- svytable(~hhr_benefits_emp_2,design) %>% as.data.frame()%>%
  mutate(percentage = round(Freq/sum(Freq)*100,2),
         hhr_benefits_emp_2 = case_when(hhr_benefits_emp_2 == "1" ~ "With gratuity",
                   hhr_benefits_emp_2 == "0" ~ "Without gratuity",
                     TRUE ~ NA))

gratuity$hhr_benefits_emp_2 <- str_wrap(as.character(gratuity$hhr_benefits_emp_2), width = 10)
p1 <- 
  ggplot(gratuity, aes(x = hhr_benefits_emp_2, y = Freq)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Gratuity - HH",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

hc_wp <- workplace_df%>%
  group_by(empl_benefits_emp_2)%>%
  summarise(count = n())%>%
  filter(!is.na(empl_benefits_emp_2))%>%
    mutate(percentage = round(count/sum(count)*100,2),
           empl_benefits_emp_2 = case_when(empl_benefits_emp_2 == 1 ~ "With Gratuity ",
                                          empl_benefits_emp_2 == 0 ~ "Without Gratuity",
                                          TRUE ~ NA))
hc_wp$empl_benefits_emp_2 <- str_wrap(as.character(hc_wp$empl_benefits_emp_2), width = 10)

p2 <- 
  ggplot(hc_wp, aes(x = empl_benefits_emp_2, y = count)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Gratuity- WP",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

p1 + p2


```


```{r}
healthcare_maternity <- svytable(~hhr_benefits_emp_3, design) %>%
  as.data.frame() %>%
  mutate(percentage = round(Freq/sum(Freq)*100,2),
        hhr_benefits_emp_3 = case_when(hhr_benefits_emp_3 == 1 ~ "With health/maternity benefits",
                   hhr_benefits_emp_3 == 0 ~ "Without health/maternity benefits"))

healthcare_maternity$hhr_benefits_emp_3 <- str_wrap(as.character(healthcare_maternity$hhr_benefits_emp_3), width = 10)
p1 <- 
  ggplot(healthcare_maternity, aes(x = hhr_benefits_emp_3, y = Freq)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Healthcare - HH",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

hcm_wp <- workplace_df%>%
  group_by(empl_benefits_emp_3)%>%
  summarise(count = n())%>%
  filter(!is.na(empl_benefits_emp_3))%>%
    mutate(percentage = round(count/sum(count)*100,2),
           empl_benefits_emp_3 = case_when(empl_benefits_emp_3 == "1" ~ "With health/maternity benefits",
                                          empl_benefits_emp_3 == "0" ~ "Without health/maternity benefits",
                                          TRUE ~ NA))

hcm_wp$empl_benefits_emp_3<- str_wrap(as.character(hcm_wp$empl_benefits_emp_3), width = 10)
                                     
p2 <- 
  ggplot(hcm_wp, aes(x = empl_benefits_emp_3, y = count)) +  
  geom_bar(stat = "identity",position = position_dodge(width = 0.8), fill = "steelblue") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), 
                hjust = -0.1, size = 3) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Healthcare - WP",
           x = NULL,
           y = "Count") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.2))) +
  theme(
    plot.title = element_text(size = 11),
    axis.text.y = element_text(size = 8),  # Adjust label size for better readability
    plot.margin = margin(2, 2, 2, 2, "cm")  # Increased margins to accommodate long labels
    )

p1 + p2



```




